defmodule TestLens.Dashboard do
  @moduledoc """
  Generates the TestLens dashboard — a single-file, zero-dependency
  static SPA that renders TestLens artifacts in the browser.

  The dashboard reads `_build/test_lens/agent.json` and
  `_build/test_lens/advice.json` (when present) and renders them as a
  tabbed view: Summary / Failures / Repair Queue / OTP Snapshots /
  Architecture Findings.

  No build step. No JS framework. No external assets. The output is a
  single `index.html` file plus an `app.js` and `app.css`, all
  self-contained.
  """

  @default_dir "_build/test_lens/dashboard"
  @index_filename "index.html"
  @app_js_filename "app.js"
  @app_css_filename "app.css"

  @doc "Returns the default dashboard output directory."
  @spec default_dir() :: String.t()
  def default_dir, do: @default_dir

  @doc """
  Generate the dashboard artifacts into `dir` (defaults to
  `_build/test_lens/dashboard`). Creates `dir` if it does not exist.
  """
  @spec generate(Path.t()) :: :ok | {:error, term()}
  def generate(dir \\ @default_dir) do
    File.mkdir_p!(dir)

    results = [
      write_file(Path.join(dir, @index_filename), index_html()),
      write_file(Path.join(dir, @app_js_filename), app_js()),
      write_file(Path.join(dir, @app_css_filename), app_css())
    ]

    if Enum.all?(results, &(&1 == :ok)),
      do: :ok,
      else: Enum.find(results, &match?({:error, _}, &1))
  end

  defp write_file(path, content) do
    File.write(path, content)
  rescue
    e -> {:error, Exception.message(e)}
  end

  # ---------------------------------------------------------------------------
  # HTML
  # ---------------------------------------------------------------------------

  defp index_html do
    """
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TestLens Dashboard</title>
        <link rel="stylesheet" href="app.css">
      </head>
      <body>
        <header>
          <h1>TestLens Dashboard</h1>
          <p id="meta">Loading artifacts from <code id="base-path"></code>…</p>
        </header>

        <nav>
          <button data-tab="summary" class="tab active">Summary</button>
          <button data-tab="failures" class="tab">Failures</button>
          <button data-tab="repair" class="tab">Repair Queue</button>
          <button data-tab="otp" class="tab">OTP Snapshots</button>
          <button data-tab="arch" class="tab">Architecture Findings</button>
        </nav>

        <main id="content">Loading…</main>

        <footer>
          <p>Generated by <code>TestLens.Dashboard</code>. No external assets. No tracking.</p>
        </footer>

        <script src="app.js"></script>
      </body>
    </html>
    """
  end

  # ---------------------------------------------------------------------------
  # CSS
  # ---------------------------------------------------------------------------

  defp app_css do
    """
    :root {
      --bg: #fafafa;
      --surface: #ffffff;
      --ink: #1a1a1a;
      --muted: #6a6a6a;
      --accent: #0a5dc2;
      --warn: #b77900;
      --critical: #c4314b;
      --info: #0a5dc2;
      --rule: #d0d0d0;
    }
    @media (prefers-color-scheme: dark) {
      :root { --bg:#161616; --surface:#1f1f1f; --ink:#e6e6e6; --muted:#9a9a9a; --rule:#3a3a3a; }
    }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--ink); line-height: 1.5; }
    header, footer { padding: 1rem 1.5rem; background: var(--surface); border-bottom: 1px solid var(--rule); }
    footer { border-top: 1px solid var(--rule); border-bottom: none; font-size: 0.85rem; color: var(--muted); }
    h1 { margin: 0; font-size: 1.5rem; }
    nav { display: flex; gap: 0.25rem; padding: 0.5rem 1.5rem; background: var(--surface); border-bottom: 1px solid var(--rule); flex-wrap: wrap; }
    .tab { background: transparent; border: 1px solid transparent; padding: 0.4rem 0.8rem; border-radius: 4px; cursor: pointer; color: var(--ink); }
    .tab:hover { background: var(--bg); border-color: var(--rule); }
    .tab.active { background: var(--bg); border-color: var(--rule); font-weight: 600; }
    main { padding: 1.5rem; max-width: 1200px; margin: 0 auto; }
    .card { background: var(--surface); border: 1px solid var(--rule); border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 0.5rem; }
    .stat { background: var(--bg); border: 1px solid var(--rule); border-radius: 6px; padding: 0.5rem 0.75rem; }
    .stat .num { font-size: 1.5rem; font-weight: 600; }
    .stat .label { font-size: 0.7rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
    .severity-critical { color: var(--critical); font-weight: 600; }
    .severity-warn { color: var(--warn); font-weight: 500; }
    .severity-info { color: var(--info); }
    .tag { display: inline-block; background: var(--bg); border: 1px solid var(--rule); padding: 0.05rem 0.45rem; border-radius: 3px; font-size: 0.8rem; margin-right: 0.25rem; }
    .muted { color: var(--muted); }
    pre { background: var(--bg); border: 1px solid var(--rule); border-radius: 6px; padding: 0.75rem; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word; font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 0.85rem; }
    details { background: var(--surface); border: 1px solid var(--rule); border-radius: 6px; padding: 0.5rem 0.75rem; margin-bottom: 0.5rem; }
    summary { cursor: pointer; font-weight: 500; }
    .empty { color: var(--muted); font-style: italic; }
    """
  end

  # ---------------------------------------------------------------------------
  # JS
  # ---------------------------------------------------------------------------

  defp app_js do
    """
    (function () {
      "use strict";

      const $ = (sel) => document.querySelector(sel);
      const $$ = (sel) => Array.from(document.querySelectorAll(sel));

      const state = {
        activeTab: "summary",
        agent: null,
        advice: null,
        loadErrors: []
      };

      async function fetchJSON(path) {
        try {
          const res = await fetch(path);
          if (!res.ok) throw new Error("HTTP " + res.status);
          return await res.json();
        } catch (e) {
          state.loadErrors.push(path + ": " + e.message);
          return null;
        }
      }

      function el(tag, attrs, children) {
        const node = document.createElement(tag);
        if (attrs) {
          for (const [k, v] of Object.entries(attrs)) {
            if (k === "class") node.className = v;
            else if (k === "text") node.textContent = v;
            else if (k.startsWith("data-")) node.setAttribute(k, v);
            else if (k === "html") node.innerHTML = v;
            else node.setAttribute(k, v);
          }
        }
        if (children) {
          for (const c of children) {
            if (typeof c === "string") node.appendChild(document.createTextNode(c));
            else if (c) node.appendChild(c);
          }
        }
        return node;
      }

      function severityClass(s) {
        return "severity-" + s;
      }

      function renderSummary() {
        const a = state.agent;
        if (!a) return el("p", { class: "empty" }, ["No agent artifact loaded."]);
        const t = a.totals || {};
        const out = el("div", null, [
          el("div", { class: "card" }, [
            el("h2", null, ["Run"]),
            el("p", null, [
              el("span", { class: "muted" }, ["Schema "]),
              el("code", null, [a.schema_version || "?"]),
              el("span", { class: "muted" }, [" · TestLens "]),
              el("code", null, [a.test_lens_version || "?"])
            ]),
            el("p", null, [el("code", null, [JSON.stringify(a.run || {}, null, 2)])])
          ]),
          el("div", { class: "card" }, [
            el("h2", null, ["Totals"]),
            el("div", { class: "grid" }, [
              stat("tests", t.tests),
              stat("passed", t.passed),
              stat("failed", t.failed),
              stat("skipped", t.skipped),
              stat("invalid", t.invalid),
              stat("excluded", t.excluded)
            ])
          ])
        ]);
        if (a.repair_queue) {
          out.appendChild(el("div", { class: "card" }, [
            el("h2", null, ["Repair Queue (" + a.repair_queue.length + ")"]),
            el("p", { class: "muted" }, ["Ranked by priority + confidence. See Repair Queue tab for details."])
          ]));
        }
        if (a.otp_snapshots && a.otp_snapshots.length > 0) {
          out.appendChild(el("div", { class: "card" }, [
            el("h2", null, ["OTP Snapshots (" + a.otp_snapshots.length + ")"]),
            el("p", { class: "muted" }, ["Captured at the moment each test failed. See OTP Snapshots tab."])
          ]));
        }
        if (a.architecture_findings && a.architecture_findings.length > 0) {
          out.appendChild(el("div", { class: "card" }, [
            el("h2", null, ["Architecture Findings (" + a.architecture_findings.length + ")"]),
            el("p", { class: "muted" }, ["Static AST + supervisor topology findings. See Architecture tab."])
          ]));
        }
        return out;
      }

      function stat(label, n) {
        return el("div", { class: "stat" }, [
          el("div", { class: "num" }, [String(n == null ? "?" : n)]),
          el("div", { class: "label" }, [label])
        ]);
      }

      function renderFailures() {
        const a = state.agent;
        if (!a || !a.failures) return el("p", { class: "empty" }, ["No failures."]);
        if (a.failures.length === 0) return el("p", { class: "empty" }, ["No failures in this run."]);
        return el("div", null, a.failures.map(f => {
          const det = el("details", null, [
            el("summary", null, [
              el("span", { class: severityClass(f.severity) }, [(f.severity || "?").toUpperCase()]),
              " ",
              el("strong", null, [f.module || "?"]),
              " > ",
              el("span", null, [f.name || "?"])
            ]),
            el("div", null, [
              el("p", null, [el("span", { class: "muted" }, ["id: "]), el("code", null, [f.id || "?"])]),
              el("p", null, [el("span", { class: "muted" }, ["file: "]), el("code", null, [f.file || "?"])]),
              f.classification ? el("pre", null, [JSON.stringify(f.classification, null, 2)]) : null,
              f.impact ? el("pre", null, [JSON.stringify(f.impact, null, 2)]) : null,
              f.app_stacktrace ? el("pre", null, [JSON.stringify(f.app_stacktrace, null, 2)]) : null,
              f.hypotheses ? el("div", null, f.hypotheses.map(h => el("p", null, [h.summary || JSON.stringify(h)]))) : null,
              f.rerun_command ? el("p", null, [el("code", null, [f.rerun_command])]) : null
            ])
          ]);
          return det;
        }));
      }

      function renderRepair() {
        const a = state.agent;
        if (!a || !a.repair_queue) return el("p", { class: "empty" }, ["No repair queue."]);
        if (a.repair_queue.length === 0) return el("p", { class: "empty" }, ["Repair queue is empty."]);
        return el("div", null, a.repair_queue.map(r => el("div", { class: "card" }, [
          el("h2", null, [
            el("span", { class: severityClass(r.priority) }, [(r.priority || "?").toUpperCase()]),
            " ",
            r.summary || r.id
          ]),
          el("p", { class: "muted" }, ["confidence: " + (r.confidence || "?")]),
          r.evidence && r.evidence.length ? el("div", null, [el("strong", null, ["Evidence"]), el("ul", null, r.evidence.map(e => el("li", null, [e])))]) : null,
          r.first_checks && r.first_checks.length ? el("div", null, [el("strong", null, ["First checks"]), el("ul", null, r.first_checks.map(c => el("li", null, [c])))]) : null,
          r.likely_files && r.likely_files.length ? el("div", null, [el("strong", null, ["Likely files"]), el("ul", null, r.likely_files.map(f => el("li", null, [el("code", null, [f])])))]) : null,
          r.verification_commands && r.verification_commands.length ? el("div", null, [el("strong", null, ["Verify"]), el("ul", null, r.verification_commands.map(c => el("li", null, [el("code", null, [c])])))]) : null
        ])));
      }

      function renderOTP() {
        const a = state.agent;
        if (!a || !a.otp_snapshots) return el("p", { class: "empty" }, ["No OTP snapshots."]);
        if (a.otp_snapshots.length === 0) return el("p", { class: "empty" }, ["OTP snapshots were not captured for this run. Re-run with --snapshot."]);
        return el("div", null, a.otp_snapshots.map(s => el("details", { class: "card" }, [
          el("summary", null, [s.snapshot_id + " — " + (s.test_module || "?") + " > " + (s.test_name || "?")]),
          el("div", null, [
            el("p", null, [el("span", { class: "muted" }, ["captured_at: "]), el("code", null, [s.captured_at || "?"])]),
            s.process_info ? el("pre", null, [JSON.stringify(s.process_info, null, 2)]) : null,
            s.supervision_subtree && s.supervision_subtree.length ? el("div", null, [el("strong", null, ["Supervision subtree"]), el("pre", null, [JSON.stringify(s.supervision_subtree, null, 2)])]) : null,
            s.telemetry_events && s.telemetry_events.length ? el("div", null, [el("strong", null, ["Telemetry events (" + s.telemetry_events.length + ")"]), el("pre", null, [JSON.stringify(s.telemetry_events.slice(0, 10), null, 2)])]) : null
          ])
        ])));
      }

      function renderArch() {
        const findings = (state.agent && state.agent.architecture_findings) || (state.advice && state.advice.findings) || [];
        if (findings.length === 0) return el("p", { class: "empty" }, ["No architecture findings. Re-run with --advise."]);
        return el("div", null, findings.map(f => el("div", { class: "card" }, [
          el("h2", null, [
            el("span", { class: severityClass(f.severity) }, [(f.severity || "?").toUpperCase()]),
            " ",
            f.rule_id || "?",
            el("span", { class: "muted" }, [" — confidence " + (f.confidence || "?")])
          ]),
          el("p", null, [el("code", null, [f.id || "?"])]),
          f.evidence ? el("p", null, [f.evidence]) : null,
          f.explanation ? el("p", { class: "muted" }, [f.explanation]) : null,
          f.remediation ? el("p", null, [el("strong", null, ["Remediation: "]), f.remediation]) : null,
          f.related_modules && f.related_modules.length ? el("p", null, [el("strong", null, ["Related: "]), f.related_modules.map(m => el("span", { class: "tag" }, [m]))]) : null,
          f.location && (f.location.file || f.location.line) ? el("p", null, [el("span", { class: "muted" }, ["at "]), el("code", null, [(f.location.file || "?") + ":" + (f.location.line || "?")])]) : null
        ])));
      }

      const renderers = {
        summary: renderSummary,
        failures: renderFailures,
        repair: renderRepair,
        otp: renderOTP,
        arch: renderArch
      };

      function render() {
        const main = $("#content");
        main.innerHTML = "";
        const fn = renderers[state.activeTab] || renderSummary;
        main.appendChild(fn());
      }

      async function load() {
        const base = location.pathname.endsWith("/") ? location.pathname : location.pathname.replace(/[^/]*$/, "");
        $("#base-path").textContent = base;
        state.agent = await fetchJSON(base + "../agent.json");
        state.advice = await fetchJSON(base + "../advice.json");

        if (state.loadErrors.length > 0) {
          const meta = $("#meta");
          const warn = el("p", { class: "muted" }, ["⚠ " + state.loadErrors.join("; ")]);
          meta.appendChild(warn);
        }

        render();
      }

      function switchTab(name) {
        state.activeTab = name;
        $$(".tab").forEach(b => b.classList.toggle("active", b.dataset.tab === name));
        render();
      }

      $$(".tab").forEach(b => b.addEventListener("click", () => switchTab(b.dataset.tab)));
      window.addEventListener("DOMContentLoaded", load);
      if (document.readyState !== "loading") load();
    })();
    """
  end
end
